const {expect}=require('chai');const{ethers}=require('hardhat');const{time}=require('@nomicfoundation/hardhat-network-helpers');const{mintInBatches}=require('./helpers/mint-batches.cjs');
async function fixture(){const[o,a,b,team,prize,audit]=await ethers.getSigners();const g=await(await ethers.getContractFactory('GenesisHorses')).deploy('placeholder');const u=await(await ethers.getContractFactory('MockUSDC')).deploy();const deadline=(await time.latest())+10000;const sale=await(await ethers.getContractFactory('HOFGenesisSale')).deploy(u.target,g.target,deadline,prize.address,audit.address,o.address);await g.setSaleContract(sale.target);await g.setTeamWallet(team.address);for(const w of[a,b]){await u.mint(w.address,60000_000000n);await u.connect(w).approve(sale.target,60000_000000n);}return{o,a,b,team,g,u,sale,deadline};}
describe('V7 mint cap 25',function(){
 it('accepts 25 and rejects 26 for Public, Community and Team',async()=>{const{a,team,g,sale}=await fixture();expect(await g.MAX_MINT_PER_TX()).eq(25);expect(await sale.MAX_MINT_PER_TX()).eq(25);await sale.connect(a).mint(25);await g.ownerMint(a.address,25);await g.ownerMint(team.address,25);await expect(sale.connect(a).mint(26)).revertedWith('Mint batch exceeds 25');for(const w of[a,team])await expect(g.ownerMint(w.address,26)).revertedWith('Mint batch exceeds 25');});
 it('enforces cap on direct saleMint even for the configured sale',async()=>{const[o,a]=await ethers.getSigners();const g=await(await ethers.getContractFactory('GenesisHorses')).deploy('p');await g.setSaleContract(o.address);await g.saleMint(a.address,25);await expect(g.saleMint(a.address,26)).revertedWith('Mint batch exceeds 25');});
 it('mints 100 Public as four transactions with unique IDs',async()=>{const{a,g,sale}=await fixture();for(let i=0;i<4;i++)await sale.connect(a).mint(25);expect(await sale.paidBy(a.address)).eq(3000_000000n);expect(await g.nextTokenId()).eq(101);for(let id=1;id<=100;id++)expect(await g.ownerOf(id)).eq(a.address);});
 it('fills independent 111 allocations and preserves Team lock',async()=>{const{a,b,team,g}=await fixture();await mintInBatches(g,'ownerMint',[a.address,111]);await mintInBatches(g,'ownerMint',[team.address,111]);expect(await g.communityAllocationMinted()).eq(111);expect(await g.teamReserveMinted()).eq(111);expect(await g.publicMinted()).eq(0);await expect(g.ownerMint(b.address,1)).revertedWith('Community allocation exceeded');await expect(g.ownerMint(team.address,1)).revertedWith('Team Reserve allocation exceeded');await expect(g.connect(team).transferFrom(team.address,b.address,112)).revertedWith('Team Reserve locked until sell-out');await g.connect(a).transferFrom(a.address,b.address,1);});
 it('preserves earlier batches when a competing buyer consumes remaining supply',async()=>{const{a,b,g,sale}=await fixture();await mintInBatches(sale.connect(b),'mint',[1950]);await sale.connect(a).mint(25);await sale.connect(b).mint(25);await expect(sale.connect(a).mint(25)).revertedWith('public supply exceeded');expect(await g.balanceOf(a.address)).eq(25);expect(await sale.sold()).eq(2000);});
 it('stops at exact deadline between batches',async()=>{const{a,g,sale,deadline}=await fixture();await time.setNextBlockTimestamp(deadline-1);await sale.connect(a).mint(25);await time.setNextBlockTimestamp(deadline);await expect(sale.connect(a).mint(25)).revertedWith('sale ended');expect(await g.balanceOf(a.address)).eq(25);});
 it('keeps first batch after insufficient USDC or allowance',async()=>{const{a,b,g,u,sale}=await fixture();await sale.connect(a).mint(25);await u.connect(a).transfer(b.address,await u.balanceOf(a.address));await expect(sale.connect(a).mint(25)).reverted;expect(await sale.sold()).eq(25);await u.connect(b).transfer(a.address,750_000000n);await u.connect(a).approve(sale.target,0);await expect(sale.connect(a).mint(25)).reverted;expect(await g.nextTokenId()).eq(26);});
 it('reverts the entire batch and payment when recipient rejects a later NFT',async()=>{const{g,u,sale}=await fixture();const r=await(await ethers.getContractFactory('MintReceiver')).deploy();await u.mint(r.target,750_000000n);await expect(r.buy(sale.target,u.target,25,3,false)).revertedWith('recipient rejected');expect(await sale.sold()).eq(0);expect(await g.nextTokenId()).eq(1);expect(await u.balanceOf(r.target)).eq(750_000000n);expect(await r.received()).eq(0);});
 it('blocks receiver callback mint reentrancy',async()=>{const{g,u,sale}=await fixture();const r=await(await ethers.getContractFactory('MintReceiver')).deploy();await u.mint(r.target,1000_000000n);await r.buy(sale.target,u.target,25,0,true);expect(await r.reentered()).eq(false);expect(await r.received()).eq(25);expect(await sale.sold()).eq(25);expect(await g.balanceOf(r.target)).eq(25);});
 it('retains current-owner refund, burn, lifetime counters and delayed reveal',async()=>{const{a,b,g,u,sale,deadline}=await fixture();await sale.connect(a).mint(25);await sale.connect(a).mint(25);expect(await g.tokenURI(1)).eq('placeholder');await g.reveal('ipfs://base/');expect(await g.tokenURI(1)).eq('ipfs://base/1.json');await expect(g.reveal('other')).revertedWith('Already revealed');await g.connect(a).transferFrom(a.address,b.address,1);await time.increaseTo(deadline);const balance=await u.balanceOf(b.address);await sale.connect(b).refund([1]);expect(await u.balanceOf(b.address)).eq(balance+30_000000n);await expect(g.ownerOf(1)).reverted;await expect(sale.connect(b).refund([1])).revertedWith('Not public sale token');expect(await g.nextTokenId()).eq(51);expect(await g.publicMinted()).eq(50);});
 it('measures cold/warm Public, Community and Team batches of 25',async()=>{const rows=[];for(const kind of['public','community','team']){const{a,team,g,sale}=await fixture();for(let i=0;i<2;i++){const tx=kind==='public'?await sale.connect(a).mint(25):await g.ownerMint(kind==='team'?team.address:a.address,25);const receipt=await tx.wait();rows.push({kind,batch:i+1,gas:Number(receipt.gasUsed)});expect(receipt.gasUsed).lessThan(4000000n);}}console.log('MINT_GAS '+JSON.stringify(rows));});
});
