const {expect}=require('chai');
const {ethers}=require('hardhat');
const {loadFixture,time}=require('@nomicfoundation/hardhat-network-helpers');
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto');
const {fixture,packet}=require('./helpers/sponsored.cjs');
const {SignedVoteQueue,RateLimiter,createSignedServer}=require('../lib/owner-voting/signed-service.cjs');
const config=require('../scripts/v7-canonical-config.cjs');
const queues=[];
function queue(f,extra={}){const q=new SignedVoteQueue({race:f.race,relayer:f.relayer,treasuryAddress:f.treasury.address,journal:path.join(fs.mkdtempSync(path.join(os.tmpdir(),'hof-phase1-')),'journal'),...extra});queues.push(q);return q;}
async function fresh(){const f=await fixture();const board=await(await ethers.getContractFactory('HOFTrustedLeaderboards')).deploy(f.genesis.target,f.owner.address,f.backend.address,f.team.address);return {...f,board,factory:await ethers.getContractAt('HOFCanonicalRaceFactory',await board.raceFactory())};}
async function create(f,number=1){const tx=await(await f.factory.createRace(1,1,number,(await time.latest())+100,f.key.publicKey)).wait();return tx.logs.map(l=>{try{return f.factory.interface.parseLog(l);}catch{return null;}}).find(l=>l?.name==='RaceCreated').args.race;}
describe('Phase 1 canonical provenance and configuration',function(){
 this.timeout(120000);
 it('accepts only fixed-factory Sponsored Race and rejects duplicate registration',async()=>{const f=await fresh(),r=await create(f);await f.board.registerRace(r);expect(await f.board.registeredRace(r)).eq(true);await expect(f.board.registerRace(r)).revertedWith('invalid race');});
 it('rejects malicious race with fabricated participants and scores despite matching all roles',async()=>{const f=await fresh();const r=await(await ethers.getContractFactory('TrustedRaceGasFixture')).deploy(f.genesis.target,f.owner.address,f.backend.address,f.team.address,(await time.latest())+100,2200);expect(await r.acceptedBallotCount()).eq(2200);expect(await r.pointsOf(ethers.getAddress(ethers.zeroPadValue(ethers.toBeHex(100000),20)))).eq(25);await expect(f.board.registerRace(r.target)).revertedWith('noncanonical race');expect(await f.board.raceCount()).eq(0);await expect(f.board.indexParticipants(0,25)).reverted;});
 it('rejects directly deployed authentic implementation without factory provenance',async()=>{const f=await fresh();const r=await(await ethers.getContractFactory('HOFRelayedRace')).deploy(f.genesis.target,(await time.latest())+100,f.team.address,f.owner.address,f.backend.address,f.key.publicKey);await expect(f.board.registerRace(r.target)).revertedWith('noncanonical race');});
 it('rejects a canonical race belonging to another board',async()=>{const f=await fresh();await expect(f.board.registerRace(f.race.target)).revertedWith('noncanonical race');});
 it('rejects wrong chapter and season at factory and wrong ordinal at board',async()=>{const f=await fresh(),opening=(await time.latest())+100;await expect(f.factory.createRace(2,1,1,opening,f.key.publicKey)).revertedWith('wrong chapter/season');await expect(f.factory.createRace(1,2,1,opening,f.key.publicKey)).revertedWith('wrong chapter/season');await expect(f.board.registerRace(await create(f,2))).revertedWith('noncanonical race');});
 it('rejects unauthorized creation and registration',async()=>{const f=await fresh();await expect(f.factory.connect(f.relayer).createRace(1,1,1,(await time.latest())+100,f.key.publicKey)).revertedWith('only HOF owner');await expect(f.board.connect(f.relayer).registerRace(await create(f))).revertedWithCustomError(f.board,'OwnableUnauthorizedAccount');});
 it('preserves six seasons and Chapter 2 boundary with 60 genuine factory races',async()=>{
  const f=await fresh();let last;
  const {preparePrizeScan}=require('./helpers/trusted-settlement.cjs');
  const {buildRelayedResult}=require('../lib/owner-voting/signed-backend.cjs');
  for(let season=1;season<=6;season++){
   const start=(await time.latest())+100;
   for(let number=1;number<=10;number++){
    const receipt=await(await f.factory.createRace(1,season,number,start+(number-1)*259200,f.key.publicKey)).wait();
    const address=receipt.logs.map(l=>{try{return f.factory.interface.parseLog(l);}catch{return null;}}).find(l=>l?.name==='RaceCreated').args.race;
    await f.board.registerRace(address);last=await ethers.getContractAt('HOFRelayedRace',address);last.scanFromBlock=receipt.blockNumber;
    await time.increaseTo(Number(await last.closesAt()));await last.freeze();
    const result=await buildRelayedResult(last,f.backend,f.key.privateKey);
    await last.proposeResult(result.totals,result.root,result.signature);await last.finalize();
   }
   await preparePrizeScan(f.board);await f.board.finalizeSeason();
  }
  expect(await f.board.raceCount()).eq(60);expect(await f.board.seasonsFinalized()).eq(6);
  const end=Number(await last.revealedAt());await time.setNextBlockTimestamp(end+30*86400-1);await expect(f.board.activateChapter2()).revertedWith('Chapter gap below 30 days');
  await time.setNextBlockTimestamp(end+30*86400);await f.board.activateChapter2();await expect(f.board.activateChapter2()).revertedWith('Chapter 2 already active');
 });
 it('requires complete config, separate operational roles and valid RSA public key',async()=>{const f=await loadFixture(fixture);const env={HOF_TOKEN_MODE:'testnetMockUSDC',HOF_OWNER_ADDRESS:f.owner.address,HOF_ADMISSION_SIGNER:f.backend.address,HOF_RELAYER_ADDRESS:f.relayer.address,TEAM_RESERVE_WALLET:f.team.address,PROJECT_WALLET:f.treasury.address,HOF_USDC_ADDRESS:f.genesis.target,AUDIT_WALLET:f.voters[0].address,MINT_DEADLINE_UNIX:'9999999999',GENESIS_PLACEHOLDER_URI:'ipfs://placeholder'};expect(config.systemConfig(env).owner).eq(f.owner.address);for(const key of Object.keys(env)){const bad={...env};delete bad[key];expect(()=>config.systemConfig(bad)).throws('Missing');}expect(()=>config.systemConfig({...env,HOF_RELAYER_ADDRESS:f.owner.address})).throws('separate');expect(()=>config.raceConfig({...env,HOF_RACE_PUBLIC_KEY:'0x1234'})).throws();expect(()=>config.raceConfig({...env,HOF_RACE_PUBLIC_KEY:f.key.publicKey,HOF_TRUSTED_LEADERBOARDS:f.board.target,GENESIS_SALE_ADDRESS:f.genesis.target,RACE_OPENS_AT_UNIX:'12345'})).not.throws();});
 it('fails closed on wrong chain, missing token bytecode, decimals and expired deadline',async()=>{const f=await loadFixture(fixture);await expect(config.validateNetwork(ethers.provider)).rejectedWith('Only Robinhood');const provider=new Proxy(ethers.provider,{get(t,k){if(k==='getNetwork')return async()=>({chainId:46630n});const v=Reflect.get(t,k,t);return typeof v==='function'?v.bind(t):v;}});const good=await(await ethers.getContractFactory('MockUSDC')).deploy(),bad=await(await ethers.getContractFactory('Mock18DecimalsToken')).deploy();const eth={...ethers,provider};const c={tokenMode:"testnetMockUSDC",owner:f.owner.address,usdc:f.voters[0].address,deadline:9999999999n};await expect(config.validateSystem(eth,c,f.owner)).rejectedWith('Missing bytecode');await expect(config.validateSystem(eth,{...c,usdc:bad.target},f.owner)).rejectedWith('6 decimals');await expect(config.validateSystem(eth,{...c,usdc:good.target,deadline:0n},f.owner)).rejectedWith('deadline');await expect(config.validateSystem(eth,{...c,usdc:good.target},f.owner)).rejectedWith('placeholder URL');
 const originalFetch=global.fetch;
 try {global.fetch=async(url)=>url.endsWith('.json')?new Response(fs.readFileSync('public/genesis/unrevealed.json')):new Response(fs.readFileSync('public/brand/hof-logo.webp'),{headers:{'content-type':'image/webp'}});
 await config.validateSystem(eth,{...c,usdc:good.target,placeholder:'https://hof-fixture.example.org/genesis/unrevealed.json'},f.owner);
 } finally {global.fetch=originalFetch;}});
 it('canonical deployment sources cannot instantiate legacy voting/leaderboards or test harnesses',()=>{for(const file of ['deploy-v7-system.js','deploy-v7-race.js']){const s=fs.readFileSync(path.join(__dirname,'../scripts',file),'utf8');expect(s).not.match(/['"](?:HOFRaceVoting|HOFCommunitySeason|HOFSeasonLeaderboard|LegacyTrustedBoardHarness)['"]/);}for(const file of ['deploy/deploy-genesis.js','deploy/deploy-hof-voting.js','scripts/register-v7-race.js'])expect(fs.readFileSync(path.join(__dirname,'..',file),'utf8')).match(/^throw new Error\("Legacy/);});
});
describe('Phase 1 journal and worker recovery',function(){
 this.timeout(120000);
 afterEach(async()=>{await ethers.provider.send('evm_setAutomine',[true]);for(const q of queues.splice(0)){q.stop();while(q.busy||q.enqueuing)await new Promise(r=>setTimeout(r,10));q.close();}});
 it('concurrent enqueue cannot overwrite attempts, pending hash or newer state',async()=>{const f=await loadFixture(fixture),p=await packet(f);let release,entered;const gate=new Promise(r=>release=r),inside=new Promise(r=>entered=r);let pause=false;const race=new Proxy(f.race,{get(t,k){if(k==='submitSigned')return {staticCall:async(...args)=>{if(pause){entered();await gate;}return t.submitSigned.staticCall(...args);}};return Reflect.get(t,k,t);}});const q=queue(f,{race});pause=true;const pending=q.enqueue(p);await inside;const id=require('../lib/owner-voting/signed-ballot.cjs').digestFor(p,(await ethers.provider.getNetwork()).chainId);q.save({id,packet:p,state:'Submitted',attempts:0});q.save({...q.jobs.get(id),state:'Broadcasting',attempts:3});q.save({...q.jobs.get(id),state:'Pending',txHash:ethers.id('test transaction')});release();await pending;expect(q.jobs.get(id).attempts).eq(3);expect(q.jobs.get(id).txHash).eq(ethers.id('test transaction'));expect(q.jobs.get(id).state).eq('Pending');});
 it('rejects stale journal transitions and terminal-state rollback',async()=>{const f=await loadFixture(fixture),q=queue(f),j=await q.enqueue(await packet(f)),old=q.jobs.get(j.id);q.save({...old,state:'Rejected'});expect(()=>q.save({...old,state:'Submitted'})).throws('stale');expect(()=>q.save({...q.jobs.get(j.id),state:'Submitted'})).throws('terminal');});
 it('excludes duplicate workers on both journal and wallet across different journals',async()=>{const f=await loadFixture(fixture),q=queue(f);await q.enqueue(await packet(f));expect(()=>queue(f,{journal:q.journal})).throws('worker already');const other=queue(f);await expect(other.enqueue(await packet(f,1))).rejectedWith('worker already');});
 it('refuses journal reuse on another deployment',async()=>{const f=await loadFixture(fixture),q=queue(f);await q.enqueue(await packet(f));q.close();const other=queue(f,{journal:q.journal,race:new Proxy(f.race,{get(t,k){if(k==='target')return f.genesis.target;return Reflect.get(t,k,t);}})});await expect(other.checkRelayer()).rejectedWith('journal deployment mismatch');});
 it('recovers dead-process lock without deleting a live owner lock',()=>{const {acquire}=require('../lib/owner-voting/journal-lock.cjs'),file=path.join(fs.mkdtempSync(path.join(os.tmpdir(),'hof-lock-test-')),'lock');fs.writeFileSync(file,JSON.stringify({pid:2147483647,host:os.hostname(),namespace:require('../lib/owner-voting/journal-lock.cjs').namespace()}));const release=acquire(file);expect(()=>acquire(file)).throws('worker already');release();});
 it('never reclaims a lock from another PID namespace as a dead process',()=>{const {acquire}=require('../lib/owner-voting/journal-lock.cjs'),file=path.join(fs.mkdtempSync(path.join(os.tmpdir(),'hof-namespace-')),'lock');fs.writeFileSync(file,JSON.stringify({pid:2147483647,host:os.hostname(),namespace:'different namespace'}));expect(()=>acquire(file)).throws('manual recovery');expect(fs.existsSync(file)).eq(true);});
 it('unknown broadcast after crash never automatically retransmits after restart',async()=>{const f=await loadFixture(fixture),q=queue(f),p=await packet(f),j=await q.enqueue(p);q.save({...q.jobs.get(j.id),state:'Broadcasting',attempts:1,broadcast:{nonce:await ethers.provider.getTransactionCount(f.relayer.address),startBlock:await ethers.provider.getBlockNumber()}});q.close();const restored=queue(f,{journal:q.journal});await restored.flush();await restored.flush();expect(restored.jobs.get(j.id).state).eq('RecoveryRequired');expect(await f.race.ballotCount()).eq(0);await expect(restored.replacePending(j.id)).rejectedWith('no known');});
 it('mined nonce cancellation without inclusion is rejected without retry',async()=>{const f=await loadFixture(fixture),q=queue(f),p=await packet(f),j=await q.enqueue(p);const nonce=await ethers.provider.getTransactionCount(f.relayer.address),start=await ethers.provider.getBlockNumber();q.save({...q.jobs.get(j.id),state:'Broadcasting',attempts:1,broadcast:{nonce,startBlock:start}});await f.relayer.sendTransaction({to:f.relayer.address,value:0,nonce});await q.flush();expect(q.jobs.get(j.id).state).eq('Rejected');expect(q.jobs.get(j.id).broadcastResolved).eq(true);expect(await f.race.ballotCount()).eq(0);await f.race.connect(f.voters[0]).submitSigned(p);expect(await f.race.ballotCount()).eq(1);});
 it('RPC failure during recovery cannot cause broadcast',async()=>{const f=await loadFixture(fixture),q=queue(f),j=await q.enqueue(await packet(f));q.save({...q.jobs.get(j.id),state:'Broadcasting',attempts:1,broadcast:{nonce:0,startBlock:0},txHash:ethers.id('unknown')});const original=f.race.runner.provider.getTransactionReceipt;f.race.runner.provider.getTransactionReceipt=async()=>{throw Error('RPC timeout');};try{await expect(q.flush()).rejectedWith('RPC timeout');expect(q.jobs.get(j.id).attempts).eq(1);}finally{f.race.runner.provider.getTransactionReceipt=original;}});
 it('stuck pending transaction is not resent; explicit same-payload replacement reconciles once',async()=>{const f=await loadFixture(fixture),q=queue(f,{receiptTimeoutMs:20}),j=await q.enqueue(await packet(f));await ethers.provider.send('evm_setAutomine',[false]);await expect(q.flush()).rejected;const hash=q.jobs.get(j.id).txHash;expect(hash).a('string');await q.flush();expect(q.jobs.get(j.id).txHash).eq(hash);const replacement=await q.replacePending(j.id);expect(replacement).not.eq(hash);await ethers.provider.send('evm_mine',[]);await q.flush();expect(await f.race.ballotCount()).eq(1);expect(q.jobs.get(j.id).broadcastResolved).eq(true);});
 it('finds a mined replacement after lost RPC response and restart',async()=>{const f=await loadFixture(fixture),q=queue(f),p=await packet(f),j=await q.enqueue(p);const start=await ethers.provider.getBlockNumber(),nonce=await ethers.provider.getTransactionCount(f.relayer.address);q.save({...q.jobs.get(j.id),state:'Broadcasting',attempts:1,broadcast:{nonce,startBlock:start}});await f.race.connect(f.relayer).submitSigned(p,{nonce});q.close();const restored=queue(f,{journal:q.journal});await restored.flush();expect(restored.jobs.get(j.id).broadcastResolved).eq(true);expect(await f.race.ballotCount()).eq(1);});
});
describe('Phase 1 authenticated admission quotas',function(){
 this.timeout(120000);afterEach(()=>{for(const q of queues.splice(0))q.close();});
 it('requires private ingress config',async()=>{const f=await loadFixture(fixture),q=queue(f);expect(()=>createSignedServer({race:f.race,queue:q,ingressToken:''})).throws('ingress token');});
 it('anonymous bursts and spoofed proxy headers cannot consume legitimate wallet/race quota',async()=>{const f=await loadFixture(fixture),q=queue(f),ingressToken=crypto.randomBytes(32).toString('hex'),limiter=new RateLimiter({limit:2});const server=createSignedServer({race:f.race,admissionSigner:f.backend,privateKey:f.key.privateKey,queue:q,ingressToken,limiter});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}/vote/prepare`;const send=(body,authorized=true)=>fetch(url,{method:'POST',headers:{'x-forwarded-for':'attacker','x-real-ip':'fake',...(authorized?{Authorization:`Bearer ${ingressToken}`}:{})},body:JSON.stringify(body)});try{expect((await send({},false)).status).eq(401);for(let i=0;i<35;i++)expect((await send({})).status).eq(400);const p=await packet(f);
const outsider=ethers.Wallet.createRandom(),intent={...p.intent,voter:outsider.address};
const signature=await outsider.signTypedData(require('../lib/owner-voting/ballot.cjs').signingDomain({chainId:(await ethers.provider.getNetwork()).chainId,race:f.race.target}),require('../lib/owner-voting/signed-ballot.cjs').intentTypes,intent);
expect((await send({...p,intent,signature})).status).eq(400);expect(limiter.entries.size).eq(0);
expect((await send(p)).status).eq(200);expect((await send(p)).status).eq(200);expect((await send(p)).status).eq(429);expect((await send(await packet(f,1))).status).eq(200);expect(limiter.entries.size).eq(2);}finally{await new Promise(r=>server.close(r));}});
 it('race-scoped keys isolate limits even with the same wallet',()=>{const l=new RateLimiter({limit:1});expect(l.allow('46630:raceA:wallet')).eq(true);expect(l.allow('46630:raceA:wallet')).eq(false);expect(l.allow('46630:raceB:wallet')).eq(true);});
});
