const {expect}=require('chai'),{ethers}=require('hardhat'),{time}=require('@nomicfoundation/hardhat-network-helpers');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {fixture,packet,authorize}=require('./helpers/sponsored.cjs');
const {RaceRevealService}=require('../lib/owner-voting/race-reveal-service.cjs');
const lockDirectory=fs.mkdtempSync(path.join(os.tmpdir(),'hof-service-test-locks-'));
const live=[];const token='test-ingress-'.repeat(4);
function service(f,extra={}){const s=new RaceRevealService({board:f.board,signer:f.backend,relayer:f.relayer,treasuryAddress:f.treasury.address,directory:fs.mkdtempSync(path.join(os.tmpdir(),'hof-reveal-')),keyFor:async()=>f.key.privateKey,raceAt:a=>ethers.getContractAt('HOFRelayedRace',a),factoryAt:a=>ethers.getContractAt('HOFCanonicalRaceFactory',a),ingressToken:token,lockDirectory,allowLocal:true,...extra});live.push(s);return s;}
async function finish(s,race){for(let i=0;i<150&&!await race.finalized();i++)await s.tick();expect(await race.finalized()).eq(true);await s.tick();}
describe('V7 automatic Race Reveal service',function(){this.timeout(180000);
 afterEach(async()=>{await ethers.provider.send('evm_setAutomine',[true]);for(const s of live.splice(0))if(!s.testClosed){await s.close();s.testClosed=true;}});
 async function restart(s,f,extra={}){const directory=s.directory;await s.close();s.testClosed=true;return service(f,{directory,...extra});}
 it('recovers accepted/queued votes after restart before deadline, closes automatically and activates both boards',async()=>{const f=await fixture();let s=service(f);await s.tick();await s.queue.enqueue(await packet(f));s=await restart(s,f);await s.tick();expect(await f.race.ballotCount()).eq(1);expect(await f.board.allTimePoints(f.voters[0].address)).eq(0);await time.increaseTo(Number(await f.race.closesAt()));s=await restart(s,f);await finish(s,f.race);expect(await f.board.seasonPoints(f.voters[0].address)).eq(25);expect(await f.board.allTimePoints(f.voters[0].address)).eq(25);expect((await f.race.ranking()).map(Number)).deep.eq([8,1,2,3,4,5,6,7,9,10,11,12,13,14,15,16,17,18,19,20,21,22]);});
 it('scheduler wakes without user/manual settlement invocation',async()=>{const f=await fixture(),s=service(f,{pollMs:10});await f.race.connect(f.relayer).submitSigned(await packet(f));await time.increaseTo(Number(await f.race.closesAt()));s.start();const end=Date.now()+20000;while(!await f.race.finalized()&&Date.now()<end)await new Promise(r=>setTimeout(r,20));s.stop();expect(await f.race.finalized()).eq(true);});
 it('a single near-deadline packet flushes without waiting for25',async()=>{const f=await fixture(),s=service(f);await time.increaseTo(Number(await f.race.closesAt())-5);await s.tick();await s.queue.enqueue(await packet(f));await s.tick();expect(await f.race.ballotCount()).eq(1);await time.increaseTo(Number(await f.race.closesAt()));await finish(s,f.race);});
 it('queue-only submission never counts: a queued packet expired at deadline is excluded from the accepted set',async()=>{const f=await fixture(),s=service(f);await s.tick();await f.race.connect(f.relayer).submitSigned(await packet(f,0));await s.queue.enqueue(await packet(f,1));await time.increaseTo(Number(await f.race.closesAt()));await finish(s,f.race);expect(await f.race.acceptedBallotCount()).eq(1);expect(await f.board.allTimePoints(f.voters[0].address)).eq(25);expect(await f.board.allTimePoints(f.voters[1].address)).eq(0);});
 it('retries complete decryption after restart, never publishing partial scores',async()=>{const f=await fixture();await f.race.connect(f.relayer).submitSigned(await packet(f));await time.increaseTo(Number(await f.race.closesAt()));let s=service(f,{buildResult:async()=>{throw Error('interrupted decryption');}});await s.tick();await expect(s.tick()).rejectedWith('interrupted');expect(await f.race.proposed()).eq(false);expect(await f.board.allTimePoints(f.voters[0].address)).eq(0);s=await restart(s,f);await finish(s,f.race);});
 it('a committed but undecryptable accepted ciphertext blocks the entire reveal',async()=>{const f=await fixture(),p=await packet(f),bytes=ethers.getBytes(p.ciphertext);bytes[bytes.length-1]^=1;p.ciphertext=ethers.hexlify(bytes);p.intent.ciphertextHash=ethers.keccak256(p.ciphertext);await f.race.connect(f.relayer).submitSigned(await authorize(f,p));await time.increaseTo(Number(await f.race.closesAt()));const s=service(f);await s.tick();await expect(s.tick()).rejected;expect(await f.race.proposed()).eq(false);expect(await f.race.finalized()).eq(false);expect(await f.board.allTimePoints(f.voters[0].address)).eq(0);});
 it('missing ciphertext events cannot become a partial final result',async()=>{const f=await fixture();await f.race.connect(f.relayer).submitSigned(await packet(f));await time.increaseTo(Number(await f.race.closesAt()));const s=service(f);await s.tick();const original=ethers.provider.getLogs;ethers.provider.getLogs=async filter=>(await original.call(ethers.provider,filter)).filter(l=>{try{return f.race.interface.parseLog(l)?.name!=='EncryptedVote';}catch{return true;}});try{await expect(s.tick()).rejectedWith('incomplete ballot');expect(await f.race.proposed()).eq(false);}finally{ethers.provider.getLogs=original;}});
 it('restarts mid scoring from canonical cursor without double scoring',async()=>{const f=await fixture();await f.race.connect(f.relayer).submitBatch([await packet(f,0),await packet(f,1)]);await time.increaseTo(Number(await f.race.closesAt()));let s=service(f,{scoreBatch:1});await s.tick();await s.tick();await s.tick();expect(await f.race.processedCount()).eq(1);expect(await f.board.allTimePoints(f.voters[0].address)).eq(0);s=await restart(s,f,{scoreBatch:1});await finish(s,f.race);expect(await f.race.processedCount()).eq(2);expect(await f.board.allTimePoints(f.voters[0].address)).eq(25);const nonce=await ethers.provider.getTransactionCount(f.backend.address);await s.tick();expect(await ethers.provider.getTransactionCount(f.backend.address)).eq(nonce);});
 it('rejects duplicate service and duplicate signer worker using a different journal directory',async()=>{const f=await fixture(),s=service(f);await s.tick();expect(()=>service(f,{directory:s.directory})).throws('worker already');const other=service(f);await expect(other.tick()).rejectedWith('worker already');});
 it('zero voters finalizes a complete22-horse ranking and zero scores',async()=>{const f=await fixture(),s=service(f);await time.increaseTo(Number(await f.race.closesAt()));await finish(s,f.race);expect((await f.race.ranking()).map(Number)).deep.eq(Array.from({length:22},(_,i)=>i+1));expect(await f.race.acceptedBallotCount()).eq(0);});
 it('a foreign proposal with the same score root but modified horse totals cannot be settled',async()=>{const f=await fixture();await f.race.connect(f.relayer).submitSigned(await packet(f));await time.increaseTo(Number(await f.race.closesAt()));await f.race.freeze();const {buildRelayedResult}=require('../lib/owner-voting/signed-backend.cjs'),{signingDomain,resultTypes}=require('../lib/owner-voting/ballot.cjs'),r=await buildRelayedResult(f.race,f.backend,f.key.privateKey);r.totals[0]=r.totals[7];r.totals[7]=0n;const signature=await f.backend.signTypedData(signingDomain({race:f.race.target,chainId:(await ethers.provider.getNetwork()).chainId}),resultTypes,{recordsHash:await f.race.frozenRecordsHash(),count:1,totalVP:await f.race.totalVP(),totalsHash:ethers.keccak256(ethers.AbiCoder.defaultAbiCoder().encode(['uint256[22]'],[r.totals])),scoresRoot:r.root});await f.race.proposeResult(r.totals,r.root,signature);const s=service(f);await expect(s.tick()).rejectedWith('proposal totals mismatch');expect(await f.race.processedCount()).eq(0);expect(await f.race.finalized()).eq(false);});
 it('refuses a mismatched RSA key and any changed durable result plan',async()=>{const f=await fixture(),s=service(f,{keyFor:async()=> 'invalid private key'});await expect(s.tick()).rejected;await s.close();s.testClosed=true;const good=service(f);await time.increaseTo(Number(await f.race.closesAt()));await good.tick();good.transactions.plan(f.race.target,ethers.id('different result'));await expect(good.tick()).rejectedWith('recomputed result mismatch');expect(await f.race.proposed()).eq(false);});
 it('pending transaction survives restart and is never retried blindly; known replacement uses same nonce',async()=>{const f=await fixture();let s=service(f);await time.increaseTo(Number(await f.race.closesAt()));await ethers.provider.send('evm_setAutomine',[false]);await s.tick();const hash=s.transactions.state.pending.hash,nonce=s.transactions.state.pending.nonce;s=await restart(s,f);await s.tick();expect(s.transactions.state.pending.hash).eq(hash);await s.transactions.replacePending();expect(s.transactions.state.pending.nonce).eq(nonce);expect(s.transactions.state.pending.hash).not.eq(hash);await ethers.provider.send('evm_mine',[]);await ethers.provider.send('evm_setAutomine',[true]);await finish(s,f.race);});
 it('lost broadcast response recovers the mined transaction by nonce after restart',async()=>{const f=await fixture();const wrapped=new Proxy(f.backend,{get(t,k){if(k==='sendTransaction')return async req=>{await t.sendTransaction(req);throw Error('response lost');};const v=Reflect.get(t,k,t);return typeof v==='function'?v.bind(t):v;}});let s=service(f,{signer:wrapped});await time.increaseTo(Number(await f.race.closesAt()));await expect(s.tick()).rejectedWith('response lost');expect(s.transactions.state.pending.hash).eq(undefined);s=await restart(s,f);await finish(s,f.race);});
 it('RPC timeout cannot broadcast or bypass closure finality',async()=>{const f=await fixture(),s=service(f);await time.increaseTo(Number(await f.race.closesAt()));const original=ethers.provider.getBlock;ethers.provider.getBlock=async tag=>{if(tag==='finalized')throw Error('RPC timeout');return original.call(ethers.provider,tag);};try{await expect(s.tick()).rejectedWith('RPC timeout');expect(await f.race.frozen()).eq(false);}finally{ethers.provider.getBlock=original;}});
 it('authenticated admission endpoint remains required on the running service',async()=>{const f=await fixture(),s=service(f);await s.tick();await new Promise(r=>s.http.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${s.http.address().port}/vote/prepare`,p=await packet(f);const res=await fetch(url,{method:'POST',body:JSON.stringify(p)});expect(res.status).eq(401);const admitted=await fetch(url,{method:'POST',headers:{Authorization:`Bearer ${token}`},body:JSON.stringify(p)});expect(admitted.status).eq(200);expect(Object.keys(await admitted.json())).deep.eq(['admission']);});
});
