const{test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const Module=require('node:module');const ts=require('typescript');const React=require('react');const{act}=React;const{createRoot}=require('react-dom/client');const{JSDOM}=require('jsdom');const viem=require('viem');
function load(filename,mocks={}){filename=path.resolve(filename);const m=new Module(filename,module),local=Module.createRequire(filename);m.filename=filename;m.paths=Module._nodeModulePaths(path.dirname(filename));m.require=id=>Object.hasOwn(mocks,id)?mocks[id]:local(id);m._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText,filename);return m.exports;}
for(const failure of[false,true,'cancelled'])test(`Mint page: ${failure==='cancelled'?'cancelled replacement cannot count as mint':failure?'third batch failure preserves 50/100':'approval and progress 1/4–4/4'}`,async()=>{
 const dom=new JSDOM('<div id="root"></div>',{url:'https://hof.test'});const prior={window:global.window,document:global.document,localStorage:global.localStorage};global.window=dom.window;global.document=dom.window.document;global.localStorage=dom.window.localStorage;global.IS_REACT_ACT_ENVIRONMENT=true;
 const buyer='0x0000000000000000000000000000000000000001',sale='0x0000000000000000000000000000000000000002',usdc='0x0000000000000000000000000000000000000003';const sent=[],estimates=[],progress=[];let minted=0,serial=0,allowance=0n;
 const receipts=new Map();const provider={request:async({method,params})=>{if(method==='eth_accounts')return[buyer];if(method==='eth_chainId')return'0xb626';if(method==='eth_sendTransaction'){const tx=params[0],decoded=viem.decodeFunctionData({abi:tx.to===usdc?[{type:'function',name:'approve',inputs:[{type:'address'},{type:'uint256'}],outputs:[{type:'bool'}],stateMutability:'nonpayable'}]:[{type:'function',name:'mint',inputs:[{type:'uint256'}],outputs:[],stateMutability:'nonpayable'}],data:tx.data});const n=decoded.args.at(-1);sent.push([decoded.functionName,n]);const hash='0x'+(++serial).toString(16).padStart(64,'0');const failed=failure&&decoded.functionName==='mint'&&serial===4;if(decoded.functionName==='approve')allowance=n;else if(!failed)minted+=Number(n);const logs=decoded.functionName==='mint'&&!failed?[{address:sale,topics:[viem.keccak256(viem.toBytes('Minted(address,uint256,uint256)')),viem.pad(buyer)],data:viem.encodeAbiParameters([{type:'uint256'},{type:'uint256'}],[n,n*30_000_000n])}]:[];receipts.set(hash,{status:failed&&failure!=='cancelled'?'reverted':'success',logs});progress.push(document.body.textContent);return hash;}throw Error(method);}};
 const client={getBlock:async()=>({number:1n,timestamp:100n}),readContract:async({functionName})=>({sold:BigInt(minted),deadline:10000n,balanceOf:60000_000000n,allowance,soldOutAt:0n,saleSuccessful:false,refundsEnabled:false}[functionName]),estimateGas:async tx=>{estimates.push(tx);return 3000000n;},waitForTransactionReceipt:async({hash})=>receipts.get(hash)};
 const hof=load('src/lib/hofClient.ts');const Page=load('src/app/mint/page.tsx',{'next/link':({children,href})=>React.createElement('a',{href},children),'viem':{...viem,createPublicClient:()=>client},'@/lib/hofClient':{...hof,HOF_CONTRACTS:{sale,usdc},getEthereum:()=>provider,requestAccount:async()=>buyer}}).default;
 const root=createRoot(document.getElementById('root'));try{await act(async()=>root.render(React.createElement(Page)));const input=document.querySelector('input');await act(async()=>{Object.getOwnPropertyDescriptor(dom.window.HTMLInputElement.prototype,'value').set.call(input,'100');input.dispatchEvent(new dom.window.Event('input',{bubbles:true}));input.dispatchEvent(new dom.window.Event('change',{bubbles:true}));});
 // React's event delegation can initialize before this JSDOM; drive the real controlled handler if needed.
 const props=Object.keys(input).find(k=>k.startsWith('__reactProps'));await act(async()=>input[props].onChange({target:{value:'100'}}));
 const button=[...document.querySelectorAll('button')].find(b=>b.textContent==='MINT WITH USDC');await act(async()=>{button.click();});
 assert.deepEqual(sent[0],['approve',3000_000000n]);assert.equal(sent.filter(([m])=>m==='mint').length,failure?3:4);assert.equal(estimates.length,sent.length);
 assert(document.body.textContent.includes(failure?'50 NFT minted; 50 NFT not purchased':'100 NFT minted; 0 NFT not purchased'));
 // Capture actual progress writes through the rendered component's state setter via DOM updates between sends.
 assert.equal(JSON.parse(localStorage.getItem(Object.keys(localStorage)[0])).confirmed,failure?'50':'100');
 }finally{await act(async()=>root.unmount());Object.assign(global,prior);dom.window.close();delete global.IS_REACT_ACT_ENVIRONMENT;}
});
