const {test}=require('node:test');const assert=require('node:assert/strict');const{runMint}=require('../lib/mint/batches.cjs');
function fixture(){let serial=0;const f={states:[],messages:[],sent:[],saved:null,waits:[],readCount:0};f.state={timestamp:1n,deadline:100n,remaining:2000n,balance:60000_000000n,allowance:0n};f.options={quantity:100,save:j=>{f.saved=structuredClone(j);},progress:s=>f.messages.push(s),read:async()=>{f.readCount++;return{...f.state,...f.states.shift()};},approve:async cost=>{f.state.allowance=cost;f.sent.push(['approve',cost]);return '0x'+(++serial).toString(16).padStart(64,'0');},mint:async n=>{f.sent.push(['mint',n]);return '0x'+(++serial).toString(16).padStart(64,'0');},wait:async(hash)=>{f.waits.push(hash);return{status:'success'};}};return f;}
test('100 NFT: exact approval and progress 1/4 through 4/4; one wait per transaction',async()=>{const f=fixture();await runMint(f.options);assert.deepEqual(f.sent,[['approve',3000_000000n],...Array.from({length:4},()=>['mint',25n])]);for(let i=1;i<=4;i++)assert(f.messages.some(s=>s.startsWith(`Mint ${i}/4`)));assert.equal(f.saved.confirmed,'100');assert.equal(f.waits.length,5);assert.equal(f.readCount,5);});
for(const [name,state]of[['sold-out',{remaining:0n}],['deadline',{timestamp:100n}],['balance',{balance:0n}],['allowance',{allowance:0n}]])test(`${name} between batches preserves exactly 50 confirmed and 50 unpurchased`,async()=>{const f=fixture();f.states=[{},{},{},state];await assert.rejects(runMint(f.options));assert.equal(f.saved.confirmed,'50');assert(f.messages.at(-1).includes('50 NFT minted; 50 NFT not purchased'));assert.equal(f.sent.filter(([k])=>k==='mint').length,2);});
test('third receipt reverted: first two batches remain; no fourth send',async()=>{const f=fixture();f.options.wait=async(hash,p)=>({status:p.kind==='mint'&&f.sent.length===4?'reverted':'success'});await assert.rejects(runMint(f.options));assert.equal(f.saved.confirmed,'50');assert.equal(f.saved.pending,null);assert.equal(f.sent.length,4);});
test('pending timeout persists hash; resume checks same hash without resending that batch',async()=>{const f=fixture();let first=true;f.options.wait=async()=>{if(first){first=false;throw Error('timeout');}return{status:'success'};};await assert.rejects(runMint(f.options));const hash=f.saved.pending.hash;assert(hash);const sends=f.sent.length;await runMint({...f.options,journal:f.saved,wait:async(h)=>{if(f.sent.length===sends)assert.equal(h,hash);return{status:'success'};}});assert.equal(f.sent.filter(([k])=>k==='approve').length,1);assert.equal(f.saved.confirmed,'100');});
test('ambiguous broadcast never retries automatically, including after reload',async()=>{const f=fixture();f.options.approve=async()=>{throw Error('connection lost');};await assert.rejects(runMint(f.options));assert.equal(f.saved.pending.hash,null);let calls=0;await assert.rejects(runMint({...f.options,journal:f.saved,approve:async()=>{calls++;}}),/nonce/);assert.equal(calls,0);});
test('gas estimation failure before broadcast is safely retryable',async()=>{const f=fixture();f.options.mint=async()=>{throw Object.assign(Error('gas budget'),{notBroadcast:true});};await assert.rejects(runMint(f.options));assert.equal(f.saved.pending,null);assert.equal(f.saved.confirmed,'0');});
test('25+1 split and invalid quantities',async()=>{const f=fixture();await runMint({...f.options,quantity:26});assert.deepEqual(f.sent.filter(([k])=>k==='mint'),[['mint',25n],['mint',1n]]);for(const quantity of[0,-1,2001,'1.5'])await assert.rejects(runMint({...fixture().options,quantity}));});
test('does not send next batch while receipt remains pending',async()=>{const f=fixture();f.state.allowance=60000_000000n;let release;f.options.wait=()=>new Promise(r=>{release=()=>r({status:'success'});});const p=runMint({...f.options,quantity:25});await new Promise(r=>setImmediate(r));assert.equal(f.sent.length,1);assert.equal(f.saved.confirmed,'0');release();await p;assert.equal(f.saved.confirmed,'25');});
test('wallet rejection clears unbroadcast pending record',async()=>{const f=fixture();f.options.approve=async()=>{throw Object.assign(Error('cancelled'),{code:4001});};await assert.rejects(runMint(f.options));assert.equal(f.saved.pending,null);});
