const {test}=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
const file=path.resolve(__dirname,'../src/lib/hofClient.ts'),mod=new Module(file,module);mod.filename=file;mod.paths=module.paths;
mod._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,file);
const {requestAccount,verifyRobinhoodChain}=mod.exports;
function wallet({switchError,addError,staysWrong=false}={}){const calls=[];let chain='0x1',added=false;return {calls,request:async({method})=>{calls.push(method);if(method==='wallet_switchEthereumChain'){if(switchError&&(!added||switchError.code!==4902))throw switchError;if(!staysWrong)chain='0xb626';}if(method==='wallet_addEthereumChain'){if(addError)throw addError;added=true;}if(method==='eth_chainId')return chain;if(method==='eth_requestAccounts')return ['0x0000000000000000000000000000000000000001'];}};}
test('Refund: user rejection is propagated without trying to add chain',async()=>{const w=wallet({switchError:Object.assign(Error('rejected'),{code:4001})});await assert.rejects(requestAccount(w),/rejected/);assert.deepEqual(w.calls,['wallet_switchEthereumChain']);});
test('Refund: switch failure cannot proceed to account/transaction',async()=>{const w=wallet({switchError:Error('switch failed')});await assert.rejects(requestAccount(w),/switch failed/);assert.equal(w.calls.includes('eth_requestAccounts'),false);});
test('Refund: successful switch response with wrong actual chain is rejected',async()=>{const w=wallet({staysWrong:true});await assert.rejects(requestAccount(w),/not on Robinhood/);assert.equal(w.calls.includes('eth_requestAccounts'),false);});
test('Refund: add chain does not imply switch; re-switch and actual chain are required',async()=>{const w=wallet({switchError:Object.assign(Error('unknown chain'),{code:4902}),staysWrong:true});await assert.rejects(requestAccount(w),/not on Robinhood/);assert.deepEqual(w.calls,['wallet_switchEthereumChain','wallet_addEthereumChain','wallet_switchEthereumChain','eth_chainId']);});
test('Refund: chain addition rejection stops flow',async()=>{const w=wallet({switchError:Object.assign(Error('unknown'),{code:4902}),addError:Error('add rejected')});await assert.rejects(requestAccount(w),/add rejected/);});
test('Refund: successful add/switch re-reads chain before returning account',async()=>{const w=wallet({switchError:Object.assign(Error('unknown'),{code:4902})});assert.equal(await requestAccount(w),'0x0000000000000000000000000000000000000001');assert.equal(w.calls.filter(x=>x==='eth_chainId').length,2);});
test('Refund: chain change while requesting accounts is rejected',async()=>{const w=wallet(),original=w.request;w.request=async args=>{if(args.method==='eth_requestAccounts'){const accounts=await original(args);w.request=async()=> '0x1';return accounts;}return original(args);};await assert.rejects(requestAccount(w),/not on Robinhood/);});
test('Refund: submit-time verification rejects wrong chain and page invokes it before sending',async()=>{await assert.rejects(verifyRobinhoodChain({request:async()=> '0x1'}),/not on Robinhood/);const page=fs.readFileSync(path.resolve(__dirname,'../src/app/refund/page.tsx'),'utf8');assert.ok(page.indexOf('await verifyRobinhoodChain(ethereum)')<page.indexOf('method: "eth_sendTransaction"'));});
